'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HelpDesk.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_AutorizacionJefe() As String
            Get
                Return ResourceManager.GetString("Email_AutorizacionJefe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_CitacionTickets() As String
            Get
                Return ResourceManager.GetString("Email_CitacionTickets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_NoSatisfecha() As String
            Get
                Return ResourceManager.GetString("Email_NoSatisfecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_NuevoSeguimiento() As String
            Get
                Return ResourceManager.GetString("Email_NuevoSeguimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_NuevoTicket() As String
            Get
                Return ResourceManager.GetString("Email_NuevoTicket", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; al [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_Reasignar() As String
            Get
                Return ResourceManager.GetString("Email_Reasignar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_RecordatorioCita() As String
            Get
                Return ResourceManager.GetString("Email_RecordatorioCita", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; al [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_Satisfaccion() As String
            Get
                Return ResourceManager.GetString("Email_Satisfaccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_TicketAnulado() As String
            Get
                Return ResourceManager.GetString("Email_TicketAnulado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;div id=&quot;:no&quot; class=&quot;ii gt m1544eb6eeeec2e27 adP adO&quot;&gt;
        '''    &lt;div id=&quot;:nk&quot; class=&quot;a3s aXjCH&quot;&gt;
        '''        &lt;u&gt;&lt;/u&gt;
        '''        &lt;div style=&quot;background-color: #f6f6f6&quot;&gt;
        '''            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        '''
        '''                &lt;tbody&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td align=&quot;center&quot; height=&quot;0&quot;&gt;&lt;/td&gt;
        '''                    &lt;/tr&gt;
        '''                    &lt;tr&gt;
        '''                        &lt;td&gt;
        '''                            &lt;table cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; border=&quot;0&quot;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Email_TicketAsignado() As String
            Get
                Return ResourceManager.GetString("Email_TicketAsignado", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
